### ISSUE TITLE
got Error while executing python manage.py runserver

### ISSUE THREAD

**Issue by Abhi-khandelwal** [GFynbo/GoudaTime#9]
![screenshot from 2017-12-20 19-04-32](https://user-images.githubusercontent.com/25298686/34209612-db1555aa-e5b8-11e7-9ff7-bebf824ee9a2.png)

**Comment by GFynbo** [comment]
The readme instructions for local dev were out of date. Take a look back through them, make sure you use Python 3 and re-run `pip install -r requirements.txt` after cloning/pulling. You need to add the .env file to setup the environment with the features described in the readme and you also will need to change the database schema to sqlite3 if you don't plan on using postgresql.

This should resolve any issues.
